name: perf-test

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  perf-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'

      - run: npm ci

      - run: npm run lint

      - run: npm run prettier-check

      - name: Run performance testing script
        run: ./reassure-tests.sh

      - name: Run Danger.js
        run: npm run danger-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
